### ISSUE TITLE
some fix for documentation

### ISSUE THREAD

**Issue by norbornen** [kingpong/perl-PDF-WebKit#3]
Configuration of PDF::WebKit is configured globally by calling the
-CPDF::WebKit-configure> class method:
+CPDF::WebKit-configure-> class method:

   PDF::WebKit->configure(sub {
     # default `which wkhtmltopdf`
-    $_->wkhtmltopdf('/path/to/wkhtmltopdf');
-    $_[0]->wkhtmltopdf('/path/to/wkhtmltopdf');
  
   # default 'pdf-webkit-'
-    $_->meta_tag_prefix('my-prefix-');
-    $_[0]->meta_tag_prefix('my-prefix-');
-    $_->default_options->{'--orientation'} = 'Portrait';
-    $_[0]->default_options->{'--orientation'} = 'Portrait';
  });

**Comment by wchristian** [comment]
Alright, i committed a fix for the ->configure issue, but i'm unclear on the others. If i read the code right, stuff like $_->wkhtmltopdf should work fine. I'm closing this for now, but if you'd like to explain that one in more detail, feel free to reopen.
