### ISSUE TITLE
swap out IPC::Run for IPC::Run3?

### ISSUE THREAD

**Issue by wchristian** [kingpong/perl-PDF-WebKit#5]
IPC::Run has the problem that it does not provide a way to `binmode` the filehandles, so occasionally generated PDFs are invalid due to newline mangling.  IPC::Run3 provides roughly the same, but also provides newline fixing. Would you accept a PR that swaps them out?

**Comment by kingpong** [comment]
@wchristian Sure.  Also, if you'd like to take over maintenance of this module, you're welcome to.  As I updated the README to say, I'm not using Perl frequently anymore, so it's probably better for someone who actually uses this module to maintain it.

**Comment by wchristian** [comment]
Thanks for confirming, and sure, i'd be happy to do that.

You could assign comaint to MITHALDU on cpan. :)

**Comment by kingpong** [comment]
Great! I've added you as a committer on this repo (but feel free to fork if you prefer) and made you comaint on cpan.

**Comment by wchristian** [comment]
If you don't mind i'll keep things in this repo. No need to complicate things. :D

**Comment by wchristian** [comment]
Hm, the readme says you switched to IPC::Run because of mod_perl, is there a ticket for that somewhere?

**Comment by kingpong** [comment]
Yes and no.  Yes, I'm sure there's a ticket, but it's in an internal JIRA
at a company I don't work for any more, so No, I don't know why. Sorry,
it's been too long to remember.

**Comment by wchristian** [comment]
Alright, i left enough traces so people can find this, and replaced it. Will cut a release now.
